Fix #136: Update tests to adapt changes in document upload
wultra/powerauth-tests pull request #137
Opened 2022-11-10 09:36 UTC by banterCZ

Depends on https://github.com/wultra/enrollment-server/pull/515

2022-11-10 09:53 UTC, banterCZ commented on powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java
> +                new IdentityVerificationState(IdentityVerificationPhase.DOCUMENT_UPLOAD, IdentityVerificationStatus.IN_PROGRESS));
@kober32 Here you can see that after upload of the first document, you should expect `DOCUMENT_UPLOAD / IN_PROGRESS`

2022-11-10 13:51 UTC, romanstrobl commented
I am concerned that the tests still have:

```
powerauth.test.identity.verificationOnSubmitEnabled=true
```

Although this logic is currently disabled on server.

Are we testing the same thing?

2022-11-10 13:54 UTC, romanstrobl approved these changes
I am happy to see minimal changes in tests.

I am a bit concerned about relevance of tests since the server runs now with `verificationOnSubmitEnabled=false`, while the tests run with `verificationOnSubmitEnabled=true`. However, this could be another ticket.

2022-11-10 14:29 UTC, romanstrobl requested changes
I ran the tests and there are some failures. Postponing approval after tests are passing.

2022-11-11 10:42 UTC, banterCZ commented
Tests passed

2022-11-11 11:22 UTC, romanstrobl approved these changes
Happy to see expected changes and that these changes are minimal.

2022-11-11 11:27 UTC, romanstrobl commented
However, I still see: `verificationOnSubmitEnabled=true` in this branch, which does not correspond to backend configuration. Can we change the default value?

2022-11-11 16:06 UTC, romanstrobl approved these changes
Approved.

2022-11-11 16:12 UTC, merged