Fix #250: Consolidate liquibase scripts
wultra/powerauth-tests pull request #259
Opened 2023-10-15 22:52 UTC by jandusil

- Move db creation to pure liquibase

2023-10-15 22:52 UTC, jandusil commented
@zcgandcomp Take a look please if you can, we have discussed this with @banterCZ but we were not sure if this is the desired outcome

2023-10-16 13:20 UTC, zcgandcomp requested changes
1) remove LB from the application.properties.
2) use standard paths schema (/docs/db/powerauth-test-server) 
3) modify the Test server Dockerfile to accommodate changes
4) remove the insertion of template data

2023-10-17 10:56 UTC, zcgandcomp requested changes

2023-10-18 07:28 UTC, zcgandcomp requested changes

2023-10-18 07:28 UTC, zcgandcomp commented on .gitignore
> +powerauth-test-server/deploy/liquibase
unnecessary

2023-10-18 07:28 UTC, zcgandcomp commented on docs-private/Developer-How-To-Start.md
> +   Copy the provided `env.list.tmp` located in `power-auth-server/docker` to `power-auth-server/env.list`.
non-existing directories. Guide is a good idea in general, but omit it for now.

2023-10-18 07:28 UTC, zcgandcomp commented on powerauth-test-server/copy_liquibase.sh
just do not use the script at all. It's redundant. Use correct path in Dockerfile.

2023-10-18 07:28 UTC, zcgandcomp commented on powerauth-test-server/deploy/docker-entrypoint.sh
> +liquibase --headless=true --log-level=INFO --changeLogFile=$LB_HOME/data/powerauth-test-server/db.changelog-module.xml --username=$POWERAUTH_SERVER_DATASOURCE_USERNAME --password=$POWERAUTH_SERVER_DA
non existing environment variable `POWERAUTH_SERVER_DATASOURCE_PASSWORD`

2023-10-19 07:32 UTC, jandusil commented on powerauth-test-server/copy_liquibase.sh
After further conversation, agreed to be useful

2023-10-19 07:33 UTC, jandusil commented
Tested and running
<img width="1228" alt="image" src="https://github.com/wultra/powerauth-tests/assets/134381434/29fb69c3-e241-4c3a-8036-b22b1fe711d6">
<img width="791" alt="image" src="https://github.com/wultra/powerauth-tests/assets/134381434/83701fc5-72fe-4c63-b9aa-3d511950026f">

2023-10-19 07:48 UTC, zcgandcomp approved these changes
Looks OK.

2023-10-19 08:03 UTC, merged